export { EmailDashboardPage } from "./dashboard"
export { EmailCampaignsPage } from "./campaigns"
export { EmailTemplatesPage } from "./templates"
export { EmailSubscribersPage } from "./subscribers"
export { EmailSegmentsPage } from "./segments"
export { EmailAutomationsPage } from "./automations"
export { EmailConfigPage } from "./config"
