import { defineSchema } from "convex/server"
import {
  userProfilesTable,
  globalSettingsTable,
  storesTable,
  storeIntegrationsTable,
  externalProductMappingsTable,
  orphanProductsTable,
  teamMembersTable,
  categoriesTable,
  productsTable,
  menusTable,
  ordersTable,
  kitchenTicketsTable,
  printerSettingsTable,
  paymentsTable,
  paymentConnectionsTable,
  uberEatsConnectionsTable,
  oauthStatesTable,
  languagesTable,
  translationsTable,
  translationJobsTable,
  gameQRCodesTable,
  requiredActionsTable,
  gamesTable,
  prizesTable,
  gamePlaysTable,
  prizeRedemptionsTable,
  promotionsTable,
  promotionUsagesTable,
  favoritesTable,
  contactMessagesTable,
  emailSubscribersTable,
  emailTemplatesTable,
  emailCampaignsTable,
  emailSegmentsTable,
  emailAutomationsTable,
  emailEventsTable,
  emailConfigTable,
  cmsPagesTable,
  cmsBlocksTable,
  cmsMediaTable,
  blogCategoriesTable,
  blogTagsTable,
  blogArticlesTable,
  blogArticleTagsTable,
  ownerEntitlementsTable,
  blogAutoConfigTable,
  blogAutoQueueTable,
  blogAutoUsageTable,
  cmsTable,
  cmsHomeTable,
  cmsMenuTable,
  cmsAboutTable,
  cmsContactTable,
  cmsBlogPostsTable,
  cmsCartTable,
  cmsCheckoutTable,
  cmsTrackingTable,
  cmsSigninTable,
  cmsSignupTable,
  cmsPrivacyTable,
  cmsTermsTable,
  cms404Table,
  cmsMaintenanceTable,
  cmsAccountTable,
  systemAuditLogTable,
} from "./tables"

/**
 * BeInDigital Engine - Convex Database Schema
 *
 * Auth tables (user, session, account, verification, jwks) are managed
 * by the Better Auth component and are NOT defined here.
 *
 * This schema defines only business-specific tables.
 */
export default defineSchema({
  userProfiles: userProfilesTable,
  globalSettings: globalSettingsTable,
  stores: storesTable,
  storeIntegrations: storeIntegrationsTable,
  externalProductMappings: externalProductMappingsTable,
  orphanProducts: orphanProductsTable,
  teamMembers: teamMembersTable,
  categories: categoriesTable,
  products: productsTable,
  menus: menusTable,
  orders: ordersTable,
  kitchenTickets: kitchenTicketsTable,
  printerSettings: printerSettingsTable,
  payments: paymentsTable,
  languages: languagesTable,
  translations: translationsTable,
  translationJobs: translationJobsTable,
  gameQRCodes: gameQRCodesTable,
  requiredActions: requiredActionsTable,
  games: gamesTable,
  prizes: prizesTable,
  gamePlays: gamePlaysTable,
  prizeRedemptions: prizeRedemptionsTable,
  promotions: promotionsTable,
  promotionUsages: promotionUsagesTable,
  paymentConnections: paymentConnectionsTable,
  uberEatsConnections: uberEatsConnectionsTable,
  oauthStates: oauthStatesTable,
  favorites: favoritesTable,
  contactMessages: contactMessagesTable,
  // Email Marketing
  emailSubscribers: emailSubscribersTable,
  emailTemplates: emailTemplatesTable,
  emailCampaigns: emailCampaignsTable,
  emailSegments: emailSegmentsTable,
  emailAutomations: emailAutomationsTable,
  emailEvents: emailEventsTable,
  emailConfig: emailConfigTable,
  // CMS block-based system
  cmsPages: cmsPagesTable,
  cmsBlocks: cmsBlocksTable,
  cmsMedia: cmsMediaTable,
  // Blog system
  blogCategories: blogCategoriesTable,
  blogTags: blogTagsTable,
  blogArticles: blogArticlesTable,
  blogArticleTags: blogArticleTagsTable,
  // Auto blog
  ownerEntitlements: ownerEntitlementsTable,
  blogAutoConfig: blogAutoConfigTable,
  blogAutoQueue: blogAutoQueueTable,
  blogAutoUsage: blogAutoUsageTable,
  // CMS
  cms: cmsTable,
  cmsHome: cmsHomeTable,
  cmsMenu: cmsMenuTable,
  cmsAbout: cmsAboutTable,
  cmsContact: cmsContactTable,
  cmsBlogPosts: cmsBlogPostsTable,
  cmsCart: cmsCartTable,
  cmsCheckout: cmsCheckoutTable,
  cmsTracking: cmsTrackingTable,
  cmsSignin: cmsSigninTable,
  cmsSignup: cmsSignupTable,
  cmsPrivacy: cmsPrivacyTable,
  cmsTerms: cmsTermsTable,
  cms404: cms404Table,
  cmsMaintenance: cmsMaintenanceTable,
  cmsAccount: cmsAccountTable,
  // System
  systemAuditLog: systemAuditLogTable,
})
