import { execFileSync } from "node:child_process"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"

import { describe, expect, test } from "vitest"
import { parse } from "yaml"

import {
  ATTRIBUTION_RULES,
  exclusionsFromEvent,
  findAttribution,
  rangeMustHaveCommits,
  runSelfTest,
  SELF_TEST_CASES,
  splitAtScissors,
  stripAttribution,
} from "../../../scripts/lib/commit-attribution.mjs"

/**
 * The rule that no AI attribution reaches Git, held by something that executes.
 *
 * `CLAUDE.md` rule 10 has forbidden it since the file existed, and it was prose
 * that nothing ran. #409 measured the result over `4e625bde..3a6cb8d1`: 27
 * `Co-Authored-By:` lines and 21 session links, on 17 of those 24 commits, all
 * of them now permanent on protected history. The same window run through
 * `pnpm check:attribution` answers 17 commits and 48 lines — the same
 * measurement, which is how this guard was calibrated.
 *
 * Two layers are asserted here because the first one has already failed in a
 * way that made no sound. `core.hooksPath` was set to husky's `.husky/_`, a
 * directory husky's own generator gitignores, so it was absent from every fresh
 * clone and every linked worktree — and git runs no hook and says nothing when
 * its hooks path resolves to nothing. So: the detector (below), and the wiring
 * that makes it run (`describe("the wiring")`), because a perfect detector that
 * no job calls is what this issue is about.
 *
 * Bench-only, like `workflow-publish-gates.test.ts`: it reads the monorepo root
 * and would be meaningless on a client site.
 */

const REPO_ROOT = path.join(__dirname, "../../..")

/** What `findAttribution` returns. It is `.mjs`, so nothing here is inferred for us. */
interface Hit {
  line: number
  text: string
  rule: string
  why: string
}

/** The trailer block an agent harness appends, in the exact shape #409 measured. */
const HARNESS_FOOTER = [
  "fix(orders): stop a paid order being collected twice",
  "",
  "The card session and the cash button both wrote `paid`.",
  "",
  "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
  "Claude-Session: https://claude.ai/code/session_01Au4LwHyQs7pYXUPUrQeW5T",
  "",
].join("\n")

describe("findAttribution", () => {
  test("catches the trailer block a harness appends", () => {
    const hits = findAttribution(HARNESS_FOOTER) as Hit[]

    expect(hits.map((hit) => hit.rule)).toEqual(["co-author", "assistant-trailer"])
    expect(hits.map((hit) => hit.line)).toEqual([5, 6])
    expect(hits[0]?.text).toBe("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>")
  })

  test.each([
    ["Co-authored-by: Claude <noreply@anthropic.com>", "co-author"],
    ["Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>", "co-author"],
    ["Signed-off-by: Claude <noreply@anthropic.com>", "co-author"],
    ["Claude-Session: https://claude.ai/code/session_01Au4", "assistant-trailer"],
    ["Claude-Model: claude-opus-5", "assistant-trailer"],
    ["🤖 Generated with [Claude Code](https://claude.com/claude-code)", "generated-with"],
    ["Generated by Claude Code.", "generated-with"],
    ["See https://claude.ai/code/session_01Au4 for the transcript.", "session-link"],
  ])("refuses %j", (line, rule) => {
    const hits = findAttribution(`subject\n\n${line}\n`) as Hit[]
    expect(hits).toHaveLength(1)
    expect(hits[0]?.rule).toBe(rule)
  })

  /**
   * The cases that decide whether this guard survives. A check that fires on a
   * commit somebody had every right to write gets deleted, not fixed — and this
   * repository names `CLAUDE.md` in commit subjects routinely, because it is a
   * tracked file with a required check of its own.
   */
  test.each([
    "docs: pin CLAUDE.md's feature count to the commit it was measured at",
    "chore: make pnpm check:claude-md fail on a stale pin",
    "fix: close the refund path\n\nCo-authored-by: Jane Doe <jane@example.com>",
    "docs: describe the CLAUDE.md rule that nothing executes",
    // Claude is an ordinary French given name, and this is a French agency: a
    // colleague's co-author trailer must survive, or the guard gets deleted
    // the first time somebody's commit is refused for their own name.
    "fix: close the refund path\n\nCo-authored-by: Claude Dupont <c.dupont@beindigital.fr>",
    "fix: the header\n\nSigned-off-by: Marie Claude <marie@beindigital.fr>",
    // The domain is only attribution with an address attached to it.
    "feat(csp): allow anthropic.com in the connect-src allowlist",
    "chore: regenerate the table generated by the CLAUDE.md check",
  ])("accepts %j", (message) => {
    expect(findAttribution(message)).toEqual([])
  })

  test("a commented-out trailer is still a trailer once git has recorded it", () => {
    // `git commit -m` cleans with `whitespace`, which KEEPS comment lines:
    // `-m "subject" -m "# Co-Authored-By: Claude <noreply@anthropic.com>"`
    // records the trailer for real. Exempting `#` here would have been a hole
    // in the one layer that cannot be bypassed.
    expect(
      findAttribution("subject\n\n# Co-Authored-By: Claude <noreply@anthropic.com>\n"),
    ).toHaveLength(1)
  })

  test("it reads the whole recorded message, scissors line and all", () => {
    // The scissors split belongs to the hook, which sees a message file that
    // still holds the `-v` diff. This function reads what git RECORDED, where
    // nothing was thrown away — `--cleanup=verbatim` keeps a scissors line, and
    // stopping there would let the message decide what judges it.
    const message = [
      "chore: add the attribution guard",
      "# ------------------------ >8 ------------------------",
      "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
    ].join("\n")

    expect(findAttribution(message)).toHaveLength(1)
  })

  /**
   * A lone CR is a line separator to every editor and to `git log`'s display,
   * and git keeps one in a message. Splitting on "\\n" alone made this a single
   * line that no `^`-anchored rule could match, and an adversarial pass got a
   * trailer through the CI check that way.
   */
  test("a CR-separated trailer is still a trailer", () => {
    const hits = findAttribution(
      "feat: x\rCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\rmore body",
    ) as Hit[]

    expect(hits).toHaveLength(1)
    expect(hits[0]?.rule).toBe("co-author")
  })

  test.each([
    ["Co-authored-by: Claude AI <ai@bots.invalid>", true],
    ["Assisted-by: Anthropic Claude <a@b.c>", true],
    ["Co-authored-by: Claude 3 Opus <bot@x.io>", true],
    // The deliberate residue, and the reason for it: this is indistinguishable
    // from a colleague. The rule enforced is "no Anthropic address and no model
    // name", which is narrower than CLAUDE.md's "no reference at all" — the
    // price of letting somebody named Claude commit.
    ["Co-authored-by: Claude <claude@example.com>", false],
  ])("a co-author trailer for %j is attribution: %s", (line, expected) => {
    expect(findAttribution(`subject\n\n${line}`).length > 0).toBe(expected)
  })

  test("an empty or absent message is not a crash", () => {
    expect(findAttribution("")).toEqual([])
    expect(findAttribution(undefined)).toEqual([])
  })
})

describe("stripAttribution", () => {
  test("removes the block and leaves a message that reads as if it were never there", () => {
    const { message, removed } = stripAttribution(HARNESS_FOOTER)

    expect(removed).toHaveLength(2)
    expect(message).toBe(
      [
        "fix(orders): stop a paid order being collected twice",
        "",
        "The card session and the cash button both wrote `paid`.",
        "",
      ].join("\n"),
    )
  })

  test("keeps a human co-author standing beside the removed one", () => {
    const { message } = stripAttribution(
      [
        "fix: close the refund path",
        "",
        "Co-authored-by: Jane Doe <jane@example.com>",
        "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
        "",
      ].join("\n"),
    )

    expect(message).toBe(
      ["fix: close the refund path", "", "Co-authored-by: Jane Doe <jane@example.com>", ""].join(
        "\n",
      ),
    )
  })

  test("leaves a clean message byte-identical", () => {
    // Reformatting somebody's message is not this hook's business, and a hook
    // that rewrites every commit is a hook that gets removed.
    const clean = "fix: something\n\n\n\nA body with deliberate spacing.\n\n\n"
    expect(stripAttribution(clean).message).toBe(clean)
  })

  test("is idempotent", () => {
    const once = stripAttribution(HARNESS_FOOTER).message
    const twice = stripAttribution(once)
    expect(twice.removed).toEqual([])
    expect(twice.message).toBe(once)
  })

  test("leaves nothing when the message was nothing else", () => {
    // The hook refuses the commit here rather than inventing a subject line.
    const { message } = stripAttribution("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    expect(message.trim()).toBe("")
  })

  test("refuses to edit a sentence rather than deleting it", () => {
    // A session link cited mid-body is attribution, but the line around it is
    // somebody's prose. Deleting the line would take the sentence with it, so
    // the hook hands it back — reported, and the message left exactly as it
    // was, so the author re-edits what they wrote.
    const prose =
      "fix: the double collection\n\nWe traced it in https://claude.ai/code/session_01x and\nfound the second writer.\n"
    const { message, removed, blocked } = stripAttribution(prose)

    expect(removed).toEqual([])
    expect(blocked).toHaveLength(1)
    expect(message).toBe(prose)
  })

  test("hands back a line that starts like a trailer and continues as prose", () => {
    // Deciding removability on the prefix alone deleted the rest of the
    // sentence — measured, with the commit still landing, cut off mid-air.
    const message =
      "docs: describe the rule\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>, which rule 10 forbids.\n"
    const { removed, blocked, message: out } = stripAttribution(message)

    expect(removed).toEqual([])
    expect(blocked).toHaveLength(1)
    expect(out).toBe(message)
  })

  test("strips a CRLF message and refuses one held together by lone CRs", () => {
    // A trailing CR is half of a line ending: a message written on Windows
    // still gets its footer removed.
    const crlf = stripAttribution(
      "feat: x\r\n\r\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\r\n",
    )
    expect(crlf.removed).toHaveLength(1)
    expect(crlf.blocked).toEqual([])

    // A CR INSIDE a line is a separator this function cannot rewrite around:
    // deleting the "\\n" line would take its other parts with it.
    const lone = stripAttribution("feat: x\rCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\rmore")
    expect(lone.removed).toEqual([])
    expect(lone.blocked).toHaveLength(1)
  })

  test("does not touch the -v diff below the scissors line", () => {
    const tail = [
      "# ------------------------ >8 ------------------------",
      "diff --git a/x b/x",
      "+Co-Authored-By: Claude <noreply@anthropic.com>",
      "",
    ].join("\n")
    const { message, removed } = stripAttribution(
      `subject\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n${tail}`,
    )

    expect(removed).toHaveLength(1)
    expect(message).toBe(`subject\n${tail}`)
    expect(splitAtScissors(message).tail).toBe(tail)
    // The `+Co-Authored-By:` in the diff is neither removed nor reported: the
    // hook must not edit the diff somebody asked to see with `git commit -v`.
    expect(stripAttribution(`subject\n\n${tail}`).blocked).toEqual([])
  })
})

describe("what a CI run examines", () => {
  test("a pull request subtracts both the base snapshot and the base branch", () => {
    // Both, because either alone is wrong somewhere: `base.sha` is the base tip
    // when the pull request was last synchronised and goes stale, and
    // `origin/main` is absent from a checkout that never fetched it.
    expect(
      exclusionsFromEvent("pull_request", {
        pull_request: { base: { sha: "abc123", ref: "main" } },
      }),
    ).toMatchObject({ refs: ["abc123", "origin/main"] })
  })

  test.each([
    ["pull_request_target", { pull_request: { base: { sha: "abc123", ref: "main" } } }, ["abc123", "origin/main"]],
    ["merge_group", { merge_group: { base_sha: "def456" } }, ["def456"]],
    ["push", { before: "0123456789abcdef" }, ["0123456789abcdef"]],
  ])("%s subtracts what its payload names", (eventName, payload, refs) => {
    expect(exclusionsFromEvent(eventName, payload)).toMatchObject({ refs })
  })

  /**
   * The reason this subtracts a branch instead of taking a two-dot range.
   * `main` carries 17 attributed commits that #409 rules out of rewriting, and
   * merging `main` into a branch is how this repository resolves a conflict —
   * so a range anchored on a stale base would fail a pull request over history
   * nobody is allowed to fix. Excluding the base branch as it stands now leaves
   * exactly the commits the pull request adds.
   */
  test("a push subtracts only what came before it", () => {
    // Subtracting the branch here would subtract the push itself and leave the
    // run examining nothing.
    expect(exclusionsFromEvent("push", { before: "abc123", ref: "refs/heads/main" })).toMatchObject({
      refs: ["abc123"],
    })
  })

  test.each([
    ["push", { before: "0000000000000000000000000000000000000000" }],
    ["push", {}],
    ["pull_request", {}],
    ["merge_group", {}],
    ["workflow_dispatch", { before: "abc123" }],
    ["pull_request", null],
  ])("%s with %j has nothing honest to subtract", (eventName, payload) => {
    expect(exclusionsFromEvent(eventName, payload)).toBeNull()
  })

  /**
   * A pull request always carries at least its own head commit, so a run that
   * examined none of them did not find a clean history — it resolved the wrong
   * scope. That is the hollow green `scripts/assert-e2e-ran.mjs` exists to
   * refuse one workflow file away, and this guard refuses it the same way.
   */
  test("an empty result is a bug on a pull request and normal on a push", () => {
    expect(rangeMustHaveCommits("pull_request")).toBe(true)
    expect(rangeMustHaveCommits("pull_request_target")).toBe(true)
    expect(rangeMustHaveCommits("merge_group")).toBe(true)
    expect(rangeMustHaveCommits("push")).toBe(false)
    expect(rangeMustHaveCommits("")).toBe(false)
  })
})

describe("the guard's own self-test", () => {
  test("passes, which is what the hook and the Lint step assert before trusting it", () => {
    expect(runSelfTest()).toEqual([])
  })

  test("keeps cases on both sides", () => {
    const expectations = SELF_TEST_CASES.map((testCase: { expect: string }) => testCase.expect)
    expect(expectations).toContain("reject")
    // Without an accepted case the rules could be widened to "anything
    // mentioning Claude" and every self-test would still pass — while every
    // commit naming CLAUDE.md started failing CI.
    expect(expectations).toContain("accept")
    expect(SELF_TEST_CASES.some((testCase: { message: string }) => /CLAUDE\.md/.test(testCase.message))).toBe(
      true,
    )
  })

  test("reports a rule that has stopped matching", () => {
    const broken = runSelfTest([
      { name: "a rule that no longer fires", message: "subject\n\nnothing to see\n", expect: "reject" },
    ])
    expect(broken).toHaveLength(1)
    expect(broken[0]).toContain("expected to reject")
  })

  test("every rule carries a reason written for whoever tripped it", () => {
    for (const rule of ATTRIBUTION_RULES as { id: string; why: string }[]) {
      expect(rule.id).toMatch(/^[a-z-]+$/)
      expect(rule.why.length).toBeGreaterThan(10)
    }
  })
})

/**
 * The hook itself, run the way git runs it: the shell script, on a message file
 * on disk. Everything above tests the detector; this tests the thing that has
 * to fire, because #409 is a story about a perfect rule nothing executed.
 */
describe("the commit-msg hook, end to end", () => {
  const hook = path.join(REPO_ROOT, ".githooks/commit-msg")

  /** Run the hook on a temporary message file, as git does with $1. */
  const runHook = (message: string) => {
    const file = path.join(
      fs.mkdtempSync(path.join(os.tmpdir(), "commit-msg-")),
      "COMMIT_EDITMSG",
    )
    fs.writeFileSync(file, message)
    let status = 0
    try {
      execFileSync(hook, [file], { encoding: "utf8", stdio: "pipe" })
    } catch (error) {
      status = (error as { status?: number }).status ?? -1
    }
    return { status, message: fs.readFileSync(file, "utf8") }
  }

  test("strips the harness footer and lets the commit through", () => {
    const { status, message } = runHook(HARNESS_FOOTER)

    expect(status).toBe(0)
    expect(message).not.toMatch(/anthropic|Claude-Session/i)
    expect(message).toContain("fix(orders): stop a paid order being collected twice")
  })

  test("leaves a clean message untouched", () => {
    const clean = "fix: something\n\nA body.\n"
    expect(runHook(clean)).toEqual({ status: 0, message: clean })
  })

  test("blocks the commit rather than editing a sentence", () => {
    const prose = "fix: it\n\nTraced in https://claude.ai/code/session_01x, then fixed.\n"
    const { status, message } = runHook(prose)

    // Non-zero is what makes git abort the commit, and the message comes back
    // exactly as its author left it.
    expect(status).toBe(1)
    expect(message).toBe(prose)
  })

  test("blocks a message that is nothing but attribution", () => {
    expect(runHook("Co-Authored-By: Claude <noreply@anthropic.com>\n").status).toBe(1)
  })
})

/**
 * The CI layer, run against a real repository — the layer the design calls the
 * guarantee, so the one worth testing on real commits rather than on strings.
 *
 * It builds a throwaway repository, copies the three scripts into it (they
 * resolve git against their own tree, which is what makes them safe to point at
 * one), and asks the check the questions an adversarial pass asked.
 */
describe("the Lint check, against a real repository", () => {
  const scripts = [
    "scripts/check-commit-attribution.mjs",
    "scripts/strip-commit-attribution.mjs",
    "scripts/lib/commit-attribution.mjs",
  ]

  /** A repository with one clean commit, and the check installed in it. */
  const scratch = () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "attribution-"))
    const git = (...args: string[]) =>
      execFileSync("git", args, { cwd: dir, encoding: "utf8", stdio: "pipe" })

    fs.mkdirSync(path.join(dir, "scripts/lib"), { recursive: true })
    for (const file of scripts) fs.copyFileSync(path.join(REPO_ROOT, file), path.join(dir, file))

    git("init", "-q", "-b", "main")
    git("config", "user.email", "test@example.com")
    git("config", "user.name", "Test")
    // No hooks: this is the layer that has to hold when the hook did not run.
    git("config", "core.hooksPath", path.join(dir, "no-such-hooks"))
    fs.writeFileSync(path.join(dir, "a.txt"), "one\n")
    git("add", "-A")
    git("commit", "-qm", "seed: a clean commit")
    return { dir, git }
  }

  /** Commit `message` verbatim, then run the check over that one commit. */
  const check = (dir: string, git: (...args: string[]) => string, message: string) => {
    fs.appendFileSync(path.join(dir, "a.txt"), "more\n")
    git("add", "-A")
    const file = path.join(dir, "msg.txt")
    fs.writeFileSync(file, message)
    git("commit", "-q", "-F", file)

    try {
      const stdout = execFileSync(
        process.execPath,
        [path.join(dir, "scripts/check-commit-attribution.mjs"), "--range", "HEAD~1..HEAD"],
        { cwd: dir, encoding: "utf8", stdio: "pipe" },
      )
      return { status: 0, output: stdout }
    } catch (error) {
      const failure = error as { status?: number; stdout?: string; stderr?: string }
      return { status: failure.status ?? -1, output: `${failure.stdout ?? ""}${failure.stderr ?? ""}` }
    }
  }

  test("refuses an attributed commit and passes a clean one", () => {
    const { dir, git } = scratch()

    expect(check(dir, git, "feat: a clean change\n\nWith a body.\n").status).toBe(0)
    expect(
      check(dir, git, "feat: a change\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n")
        .status,
    ).toBe(1)
  })

  /**
   * The hole an adversarial pass found. The read used \x1f and \x1e to separate
   * git log's fields and records; git accepts both in a commit message, so a
   * bare \x1e made everything below it parse as the next record's sha and the
   * check exited 0 over a commit whose trailers GitHub was displaying in full.
   * NUL is the one byte that cannot be forged — `git commit` answers
   * `error: a NUL byte in commit log message not allowed` and writes no object.
   */
  test("a control byte in the message does not hide the trailer", () => {
    const { dir, git } = scratch()
    const result = check(
      dir,
      git,
      "feat: a normal-looking change\n\nSome notes.\u001e\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n",
    )

    expect(result.status).toBe(1)
    expect(result.output).toContain("Co-Authored-By")
  })

  test("a CR-separated trailer does not hide either", () => {
    const { dir, git } = scratch()
    const result = check(
      dir,
      git,
      "feat: a change\rCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\rand more\n",
    )

    expect(result.status).toBe(1)
  })

  /**
   * An empty range on a pull request means the base was wrong — except after
   * the pull request is merged, when it means every commit it added is now in
   * the base branch. Refusing that would turn a re-run of a merged pull request
   * red for nothing.
   */
  test("an empty range is refused on an open pull request and accepted on a merged one", () => {
    const { dir, git } = scratch()
    const head = git("rev-parse", "HEAD").trim()

    const run = (baseSha: string) => {
      const event = path.join(dir, "event.json")
      fs.writeFileSync(event, JSON.stringify({ pull_request: { base: { sha: baseSha, ref: "main" } } }))
      const env = {
        ...process.env,
        GITHUB_EVENT_NAME: "pull_request",
        GITHUB_EVENT_PATH: event,
      }
      try {
        return {
          status: 0,
          output: execFileSync(
            process.execPath,
            [path.join(dir, "scripts/check-commit-attribution.mjs")],
            { cwd: dir, encoding: "utf8", stdio: "pipe", env },
          ),
        }
      } catch (error) {
        const failure = error as { status?: number; stdout?: string; stderr?: string }
        return {
          status: failure.status ?? -1,
          output: `${failure.stdout ?? ""}${failure.stderr ?? ""}`,
        }
      }
    }

    // HEAD is the base: nothing was added, and HEAD is contained in it.
    const merged = run(head)
    expect(merged.status).toBe(0)
    expect(merged.output).toContain("already in the base branch")

    // A base this checkout does not contain, and no origin/main to fall back
    // to: the check refuses rather than examining nothing and reporting a pass.
    const wrong = run("0".repeat(40))
    expect(wrong.status).toBe(1)
  })
})

/**
 * The half that #409 is actually about. The detector was never the problem —
 * nothing called one. These four assertions are the ones that fail if a future
 * change quietly unhooks it.
 */
describe("the wiring", () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8")) as {
    scripts?: Record<string, string>
    devDependencies?: Record<string, string>
  }

  test("the root manifest exposes the check the Lint job runs", () => {
    expect(manifest.scripts?.["check:attribution"]).toBe("node scripts/check-commit-attribution.mjs")
  })

  test("`prepare` installs the hooks rather than husky", () => {
    // `husky` writes its wrappers into `.husky/_` and gitignores them from
    // inside, so `core.hooksPath` pointed at a directory absent from every
    // fresh checkout — no hook ran, and git said nothing. Bringing it back
    // would silently disable the commit-msg hook again.
    expect(manifest.scripts?.prepare).toBe("node scripts/install-git-hooks.mjs")
    expect(manifest.devDependencies).not.toHaveProperty("husky")
  })

  test("the commit-msg hook is tracked and executable", () => {
    // Tracked is the whole fix: a hooks directory that travels with the
    // checkout is present in every worktree, so the path cannot resolve to
    // nothing. `git ls-files -s` reports the mode git will check it out with.
    const entry = execFileSync("git", ["ls-files", "-s", ".githooks/commit-msg"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
    }).trim()

    expect(entry).not.toBe("")
    expect(entry.split(" ")[0]).toBe("100755")
  })

  test("the Lint job still runs it", () => {
    // `Lint` is required by branch protection by name, which is what makes this
    // blocking with no repository-settings change. A step deleted from here is
    // a guard switched off.
    const workflow = parse(
      fs.readFileSync(path.join(REPO_ROOT, ".github/workflows/ci.yml"), "utf8"),
    ) as { jobs: Record<string, { name?: string; steps?: { run?: string }[] }> }

    const lint = Object.values(workflow.jobs).find((job) => job.name === "Lint")
    expect(lint, "ci.yml no longer has a job named Lint").toBeDefined()
    expect(lint?.steps?.map((step) => step.run)).toContain("pnpm check:attribution")
  })
})
