import { execFileSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import { describe, expect, test } from "vitest"
import { parse } from "yaml"

import {
  ATTRIBUTION_RULES,
  exclusionsFromEvent,
  findAttribution,
  rangeMustHaveCommits,
  runSelfTest,
  SELF_TEST_CASES,
  splitAtScissors,
  stripAttribution,
} from "../../../scripts/lib/commit-attribution.mjs"

/**
 * The rule that no AI attribution reaches Git, held by something that executes.
 *
 * `CLAUDE.md` rule 10 has forbidden it since the file existed, and it was prose
 * that nothing ran. #409 measured the result over `4e625bde..3a6cb8d1`: 27
 * `Co-Authored-By:` lines and 21 session links, on 17 of those 24 commits, all
 * of them now permanent on protected history. The same window run through
 * `pnpm check:attribution` answers 17 commits and 48 lines — the same
 * measurement, which is how this guard was calibrated.
 *
 * Two layers are asserted here because the first one has already failed in a
 * way that made no sound. `core.hooksPath` was set to husky's `.husky/_`, a
 * directory husky's own generator gitignores, so it was absent from every fresh
 * clone and every linked worktree — and git runs no hook and says nothing when
 * its hooks path resolves to nothing. So: the detector (below), and the wiring
 * that makes it run (`describe("the wiring")`), because a perfect detector that
 * no job calls is what this issue is about.
 *
 * Bench-only, like `workflow-publish-gates.test.ts`: it reads the monorepo root
 * and would be meaningless on a client site.
 */

const REPO_ROOT = path.join(__dirname, "../../..")

/** What `findAttribution` returns. It is `.mjs`, so nothing here is inferred for us. */
interface Hit {
  line: number
  text: string
  rule: string
  why: string
}

/** The trailer block an agent harness appends, in the exact shape #409 measured. */
const HARNESS_FOOTER = [
  "fix(orders): stop a paid order being collected twice",
  "",
  "The card session and the cash button both wrote `paid`.",
  "",
  "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
  "Claude-Session: https://claude.ai/code/session_01Au4LwHyQs7pYXUPUrQeW5T",
  "",
].join("\n")

describe("findAttribution", () => {
  test("catches the trailer block a harness appends", () => {
    const hits = findAttribution(HARNESS_FOOTER) as Hit[]

    expect(hits.map((hit) => hit.rule)).toEqual(["co-author", "assistant-trailer"])
    expect(hits.map((hit) => hit.line)).toEqual([5, 6])
    expect(hits[0]?.text).toBe("Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>")
  })

  test.each([
    ["Co-authored-by: Claude <noreply@anthropic.com>", "co-author"],
    ["Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>", "co-author"],
    ["Signed-off-by: Claude <noreply@anthropic.com>", "co-author"],
    ["Claude-Session: https://claude.ai/code/session_01Au4", "assistant-trailer"],
    ["Claude-Model: claude-opus-5", "assistant-trailer"],
    ["🤖 Generated with [Claude Code](https://claude.com/claude-code)", "generated-with"],
    ["Generated by Claude Code.", "generated-with"],
    ["See https://claude.ai/code/session_01Au4 for the transcript.", "session-link"],
  ])("refuses %j", (line, rule) => {
    const hits = findAttribution(`subject\n\n${line}\n`) as Hit[]
    expect(hits).toHaveLength(1)
    expect(hits[0]?.rule).toBe(rule)
  })

  /**
   * The cases that decide whether this guard survives. A check that fires on a
   * commit somebody had every right to write gets deleted, not fixed — and this
   * repository names `CLAUDE.md` in commit subjects routinely, because it is a
   * tracked file with a required check of its own.
   */
  test.each([
    "docs: pin CLAUDE.md's feature count to the commit it was measured at",
    "chore: make pnpm check:claude-md fail on a stale pin",
    "fix: close the refund path\n\nCo-authored-by: Jane Doe <jane@example.com>",
    "docs: describe the CLAUDE.md rule that nothing executes",
  ])("accepts %j", (message) => {
    expect(findAttribution(message)).toEqual([])
  })

  test("a trailer in the -v diff is not a trailer on this commit", () => {
    // `git commit -v` appends the staged diff below a scissors line and throws
    // it away itself. A diff of this very file contains the strings above, so
    // without the split, adding this guard would refuse its own commit.
    const message = [
      "chore: add the attribution guard",
      "",
      "# ------------------------ >8 ------------------------",
      "diff --git a/scripts/lib/commit-attribution.mjs b/scripts/lib/commit-attribution.mjs",
      "+    message: 'Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>',",
      "",
    ].join("\n")

    expect(findAttribution(message)).toEqual([])
  })

  test("a commented-out trailer in the editor template is not the message", () => {
    expect(findAttribution("subject\n\n# Co-Authored-By: Claude <noreply@anthropic.com>\n")).toEqual(
      [],
    )
  })

  test("an empty or absent message is not a crash", () => {
    expect(findAttribution("")).toEqual([])
    expect(findAttribution(undefined)).toEqual([])
  })
})

describe("stripAttribution", () => {
  test("removes the block and leaves a message that reads as if it were never there", () => {
    const { message, removed } = stripAttribution(HARNESS_FOOTER)

    expect(removed).toHaveLength(2)
    expect(message).toBe(
      [
        "fix(orders): stop a paid order being collected twice",
        "",
        "The card session and the cash button both wrote `paid`.",
        "",
      ].join("\n"),
    )
  })

  test("keeps a human co-author standing beside the removed one", () => {
    const { message } = stripAttribution(
      [
        "fix: close the refund path",
        "",
        "Co-authored-by: Jane Doe <jane@example.com>",
        "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
        "",
      ].join("\n"),
    )

    expect(message).toBe(
      ["fix: close the refund path", "", "Co-authored-by: Jane Doe <jane@example.com>", ""].join(
        "\n",
      ),
    )
  })

  test("leaves a clean message byte-identical", () => {
    // Reformatting somebody's message is not this hook's business, and a hook
    // that rewrites every commit is a hook that gets removed.
    const clean = "fix: something\n\n\n\nA body with deliberate spacing.\n\n\n"
    expect(stripAttribution(clean).message).toBe(clean)
  })

  test("is idempotent", () => {
    const once = stripAttribution(HARNESS_FOOTER).message
    const twice = stripAttribution(once)
    expect(twice.removed).toEqual([])
    expect(twice.message).toBe(once)
  })

  test("leaves nothing when the message was nothing else", () => {
    // The hook refuses the commit here rather than inventing a subject line.
    const { message } = stripAttribution("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    expect(message.trim()).toBe("")
  })

  test("does not touch the -v diff below the scissors line", () => {
    const tail = [
      "# ------------------------ >8 ------------------------",
      "diff --git a/x b/x",
      "+Co-Authored-By: Claude <noreply@anthropic.com>",
      "",
    ].join("\n")
    const { message, removed } = stripAttribution(
      `subject\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n${tail}`,
    )

    expect(removed).toHaveLength(1)
    expect(message).toBe(`subject\n${tail}`)
    expect(splitAtScissors(message).tail).toBe(tail)
  })
})

describe("what a CI run examines", () => {
  test("a pull request subtracts both the base snapshot and the base branch", () => {
    // Both, because either alone is wrong somewhere: `base.sha` is the base tip
    // when the pull request was last synchronised and goes stale, and
    // `origin/main` is absent from a checkout that never fetched it.
    expect(
      exclusionsFromEvent("pull_request", {
        pull_request: { base: { sha: "abc123", ref: "main" } },
      }),
    ).toMatchObject({ refs: ["abc123", "origin/main"] })
  })

  test.each([
    ["pull_request_target", { pull_request: { base: { sha: "abc123", ref: "main" } } }, ["abc123", "origin/main"]],
    ["merge_group", { merge_group: { base_sha: "def456" } }, ["def456"]],
    ["push", { before: "0123456789abcdef" }, ["0123456789abcdef"]],
  ])("%s subtracts what its payload names", (eventName, payload, refs) => {
    expect(exclusionsFromEvent(eventName, payload)).toMatchObject({ refs })
  })

  /**
   * The reason this subtracts a branch instead of taking a two-dot range.
   * `main` carries 17 attributed commits that #409 rules out of rewriting, and
   * merging `main` into a branch is how this repository resolves a conflict —
   * so a range anchored on a stale base would fail a pull request over history
   * nobody is allowed to fix. Excluding the base branch as it stands now leaves
   * exactly the commits the pull request adds.
   */
  test("a push subtracts only what came before it", () => {
    // Subtracting the branch here would subtract the push itself and leave the
    // run examining nothing.
    expect(exclusionsFromEvent("push", { before: "abc123", ref: "refs/heads/main" })).toMatchObject({
      refs: ["abc123"],
    })
  })

  test.each([
    ["push", { before: "0000000000000000000000000000000000000000" }],
    ["push", {}],
    ["pull_request", {}],
    ["merge_group", {}],
    ["workflow_dispatch", { before: "abc123" }],
    ["pull_request", null],
  ])("%s with %j has nothing honest to subtract", (eventName, payload) => {
    expect(exclusionsFromEvent(eventName, payload)).toBeNull()
  })

  /**
   * A pull request always carries at least its own head commit, so a run that
   * examined none of them did not find a clean history — it resolved the wrong
   * scope. That is the hollow green `scripts/assert-e2e-ran.mjs` exists to
   * refuse one workflow file away, and this guard refuses it the same way.
   */
  test("an empty result is a bug on a pull request and normal on a push", () => {
    expect(rangeMustHaveCommits("pull_request")).toBe(true)
    expect(rangeMustHaveCommits("pull_request_target")).toBe(true)
    expect(rangeMustHaveCommits("merge_group")).toBe(true)
    expect(rangeMustHaveCommits("push")).toBe(false)
    expect(rangeMustHaveCommits("")).toBe(false)
  })
})

describe("the guard's own self-test", () => {
  test("passes, which is what the hook and the Lint step assert before trusting it", () => {
    expect(runSelfTest()).toEqual([])
  })

  test("keeps cases on both sides", () => {
    const expectations = SELF_TEST_CASES.map((testCase: { expect: string }) => testCase.expect)
    expect(expectations).toContain("reject")
    // Without an accepted case the rules could be widened to "anything
    // mentioning Claude" and every self-test would still pass — while every
    // commit naming CLAUDE.md started failing CI.
    expect(expectations).toContain("accept")
    expect(SELF_TEST_CASES.some((testCase: { message: string }) => /CLAUDE\.md/.test(testCase.message))).toBe(
      true,
    )
  })

  test("reports a rule that has stopped matching", () => {
    const broken = runSelfTest([
      { name: "a rule that no longer fires", message: "subject\n\nnothing to see\n", expect: "reject" },
    ])
    expect(broken).toHaveLength(1)
    expect(broken[0]).toContain("expected to reject")
  })

  test("every rule carries a reason written for whoever tripped it", () => {
    for (const rule of ATTRIBUTION_RULES as { id: string; why: string }[]) {
      expect(rule.id).toMatch(/^[a-z-]+$/)
      expect(rule.why.length).toBeGreaterThan(10)
    }
  })
})

/**
 * The half that #409 is actually about. The detector was never the problem —
 * nothing called one. These four assertions are the ones that fail if a future
 * change quietly unhooks it.
 */
describe("the wiring", () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8")) as {
    scripts?: Record<string, string>
    devDependencies?: Record<string, string>
  }

  test("the root manifest exposes the check the Lint job runs", () => {
    expect(manifest.scripts?.["check:attribution"]).toBe("node scripts/check-commit-attribution.mjs")
  })

  test("`prepare` installs the hooks rather than husky", () => {
    // `husky` writes its wrappers into `.husky/_` and gitignores them from
    // inside, so `core.hooksPath` pointed at a directory absent from every
    // fresh checkout — no hook ran, and git said nothing. Bringing it back
    // would silently disable the commit-msg hook again.
    expect(manifest.scripts?.prepare).toBe("node scripts/install-git-hooks.mjs")
    expect(manifest.devDependencies).not.toHaveProperty("husky")
  })

  test("the commit-msg hook is tracked and executable", () => {
    // Tracked is the whole fix: a hooks directory that travels with the
    // checkout is present in every worktree, so the path cannot resolve to
    // nothing. `git ls-files -s` reports the mode git will check it out with.
    const entry = execFileSync("git", ["ls-files", "-s", ".githooks/commit-msg"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
    }).trim()

    expect(entry).not.toBe("")
    expect(entry.split(" ")[0]).toBe("100755")
  })

  test("the Lint job still runs it", () => {
    // `Lint` is required by branch protection by name, which is what makes this
    // blocking with no repository-settings change. A step deleted from here is
    // a guard switched off.
    const workflow = parse(
      fs.readFileSync(path.join(REPO_ROOT, ".github/workflows/ci.yml"), "utf8"),
    ) as { jobs: Record<string, { name?: string; steps?: { run?: string }[] }> }

    const lint = Object.values(workflow.jobs).find((job) => job.name === "Lint")
    expect(lint, "ci.yml no longer has a job named Lint").toBeDefined()
    expect(lint?.steps?.map((step) => step.run)).toContain("pnpm check:attribution")
  })
})
