import { defineSchema } from "convex/server";
import {
  userProfilesTable,
  globalSettingsTable,
  storeIntegrationsTable,
  externalProductMappingsTable,
  orphanProductsTable,
  storesTable,
  teamMembersTable,
  categoriesTable,
  productsTable,
  menusTable,
  ordersTable,
  kitchenTicketsTable,
  printerSettingsTable,
  paymentsTable,
  paymentConnectionsTable,
  languagesTable,
  translationsTable,
  translationJobsTable,
  gameQRCodesTable,
  requiredActionsTable,
  gamesTable,
  prizesTable,
  gamePlaysTable,
  prizeRedemptionsTable,
  promotionsTable,
  promotionUsagesTable,
  emailSubscribersTable,
  emailTemplatesTable,
  emailCampaignsTable,
  emailSegmentsTable,
  emailAutomationsTable,
  emailEventsTable,
  emailConfigTable,
  cmsPagesTable,
  cmsBlocksTable,
  cmsMediaTable,
  blogCategoriesTable,
  blogTagsTable,
  blogArticlesTable,
  blogArticleTagsTable,
} from "@beindigital-engine/convex-schema";

/**
 * BeInDigital Engine - App Schema
 *
 * Auth tables (user, session, account, verification, jwks) are managed
 * by the Better Auth component and are NOT defined here.
 *
 * Business tables are imported from @beindigital-engine/convex-schema.
 */
export default defineSchema(
  {
  userProfiles: userProfilesTable,
  globalSettings: globalSettingsTable,
  storeIntegrations: storeIntegrationsTable,
  externalProductMappings: externalProductMappingsTable,
  orphanProducts: orphanProductsTable,
  stores: storesTable,
  teamMembers: teamMembersTable,
  categories: categoriesTable,
  products: productsTable,
  menus: menusTable,
  orders: ordersTable,
  kitchenTickets: kitchenTicketsTable,
  printerSettings: printerSettingsTable,
  payments: paymentsTable,
  paymentConnections: paymentConnectionsTable,
  languages: languagesTable,
  translations: translationsTable,
  translationJobs: translationJobsTable,
  gameQRCodes: gameQRCodesTable,
  requiredActions: requiredActionsTable,
  games: gamesTable,
  prizes: prizesTable,
  gamePlays: gamePlaysTable,
  prizeRedemptions: prizeRedemptionsTable,
  promotions: promotionsTable,
  promotionUsages: promotionUsagesTable,
  emailSubscribers: emailSubscribersTable,
  emailTemplates: emailTemplatesTable,
  emailCampaigns: emailCampaignsTable,
  emailSegments: emailSegmentsTable,
  emailAutomations: emailAutomationsTable,
  emailEvents: emailEventsTable,
  emailConfig: emailConfigTable,
  cmsPages: cmsPagesTable,
  cmsBlocks: cmsBlocksTable,
  cmsMedia: cmsMediaTable,
  blogCategories: blogCategoriesTable,
  blogTags: blogTagsTable,
  blogArticles: blogArticlesTable,
  blogArticleTags: blogArticleTagsTable,
  },
  { schemaValidation: false }
);
